spring:
  data:
    web:
      pageable:
        default-page-size: 20
  web:
    resources:
      add-mappings: false
  datasource:
    read-write:
      hikari:
        jdbc-url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: password
        driver-class-name: org.h2.Driver
        pool-name: 'read-write-pool'
    read-only:
      hikari:
        jdbc-url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: password
        driver-class-name: org.h2.Driver
        pool-name: 'read-only-pool'
        read-only: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
springdoc:
  swagger-ui:
    url: /docs/openapi.yaml
    path: /test/swagger.html
  api-docs:
    enabled: false
