# Ref. https://swagger.io/specification/
openapi: '3.0.3'
info:
  title: 'task'
  version: 'automatically set by codes'
servers:
  - url: 'http://localhost:8080'
    description: 'Local'
paths:
  '/api/employee':
    get:
      description: 'Get refund info'
      responses:
        200:
          description: 'Success get tax refund amount'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
    post:
      description: 'Bulk save employee by csv or json file'
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        201:
          description: 'Success save employees'
  '/api/employee/{name}':
    get:
      description: 'Get employee info by name'
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          example: '김철수'
      responses:
        200:
          description: 'Success get employee info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        404:
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                NOT_FOUND_EMPLOYEE:
                  $ref: '#/components/examples/NOT_FOUND_EMPLOYEE'
components:
  schemas:
    Error:
      type: object
      properties:
        errorMessage:
          type: string
          description: 'Error message'
    Employee:
      type: object
      properties:
        name:
          type: string
          nullable: false
          example: 김철수
        email:
          type: string
          nullable: false
          example: qweon@naver.com
        tel:
          type: string
          nullable: false
          example: 010-1111-2222
        joined:
          type: string
          nullable: false
          format: date
          example: '2024-05-18'
  examples:
    NOT_FOUND_EMPLOYEE:
      value:
        errorMessage: '회원을 찾을수 없습니다.'
