# Ref. https://swagger.io/specification/
openapi: '3.0.3'
info:
  title: 'task'
  version: 'automatically set by codes'
servers:
  - url: 'http://localhost:8080'
    description: 'Local'
paths:
  '/api/employee':
    get:
      description: 'Get employees'
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            nullable: false
            default: 1
          example: 1
      responses:
        200:
          description: 'Success get tax refund amount'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
    post:
      description: 'Bulk save employee by csv or json file'
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: |
                [
                {"name": "이무기", "email": "weapon@clovf.com", "tel": "010-1111-2424", "joined": "2020-01-05"},
                {"name": "판브이", "email": "panv@clovf.com", "tel": "010-3535-7979", "joined": "2013-07-01"},
                {"name": "차호빵1", "email": "hobread1@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵2", "email": "hobread11@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵3", "email": "hobread2@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵4", "email": "hobread23@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵5", "email": "hobread4@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵6", "email": "hobread45@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵7", "email": "hobread6@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵8", "email": "hobread33@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵9", "email": "hobread322@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵10", "email": "hobread14@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵11", "email": "hobread23@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵12", "email": "hobread@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵13", "email": "hobread@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵14", "email": "hobread@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵15", "email": "hobread@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵16", "email": "hobread@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵17", "email": "hobread@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵18", "email": "hobread@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵19", "email": "hobread@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵20", "email": "hobread@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"},
                {"name": "차호빵21", "email": "hobread@clovf.com", "tel": "010-8531-7942", "joined": "2019-12-05"}
                ]
          application/octet-stream:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        201:
          description: 'Success save employees'
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                INVALID_UPLOAD_FORMAT:
                  $ref: '#/components/examples/INVALID_UPLOAD_FORMAT'
        409:
          description: 'Conflict'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                ALREADY_EXIST_EMPLOYEE:
                  $ref: '#/components/examples/ALREADY_EXIST_EMPLOYEE'
  '/api/employee/{name}':
    get:
      description: 'Get employee info by name'
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          example: '이무기'
      responses:
        200:
          description: 'Success get employee info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        404:
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                NOT_FOUND_EMPLOYEE:
                  $ref: '#/components/examples/NOT_FOUND_EMPLOYEE'
components:
  schemas:
    Error:
      type: object
      properties:
        errorMessage:
          type: string
          description: 'Error message'
    Employee:
      type: object
      properties:
        id:
          type: integer
          nullable: false
          example: 1
        name:
          type: string
          nullable: false
          example: 이무기
        email:
          type: string
          nullable: false
          example: weapon@clovf.com
        tel:
          type: string
          nullable: false
          example: 01011112424
        joined:
          type: string
          nullable: false
          format: datetime
          example: '2020-01-05T00:00:00'
  examples:
    NOT_FOUND_EMPLOYEE:
      value:
        errorMessage: '직원을 찾을수 없습니다.'
    INVALID_UPLOAD_FORMAT:
      value:
        errorMessage: '지원하지 않는 파일 형식입니다.'
    ALREADY_EXIST_EMPLOYEE:
      value:
        errorMessage: '이미 존재하는 직원이 있습니다.'